# Generated by Django 5.1 on 2024-09-16 23:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='project_image/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(),
        ),
    ]
