# Generated by Django 5.1 on 2024-09-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image_alter_project_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_zip',
            field=models.FileField(default='VAIN.zip', upload_to='project_zips/'),
            preserve_default=False,
        ),
    ]
