# Generated by Django 5.1 on 2024-09-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_price_projectpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_zip',
            field=models.FileField(blank=True, null=True, upload_to='project_zips/'),
        ),
        migrations.AlterField(
            model_name='projectpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
