# Generated by Django 5.1 on 2024-09-22 22:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_project_url_alter_project_project_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_zip',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='project_zips/'),
        ),
    ]
