# Generated by Django 5.1 on 2024-10-07 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_alter_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
