# Generated by Django 5.1 on 2024-09-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
